mozilla-lockwise/mozilla-lockwise.github.io

architecture/fxa.md, architecture/index.md, index.md
Still lacking details for mobile
=> Document FxA Integration

process.md
These were broken since the generator doesn't know what to do with ampersands.
And I never use ampersands so, let's just use the word "and" anyway.
=> Fix TOC names and anchors

index.md
New docs site built by @sashei and BuddyBuild hooked up for CI pipeline
=> Replace Travis with BuddyBuild build and add doc link for iOS

_includes/head.html, contributing.md
resolves https://github.com/mozilla-lockbox/lockbox-extension/issues/412 (partially)
=> Remove head cruft

_includes/head.html
=> Add Jekyll SEO tag

architecture/index.md, architecture/sync.md
Resolves #25.
This is still a work in progress, but making this visible to start gathering some feedback.
=> Sync Architecture Design

.travis.yml, _includes/head.html, _includes/relativebase.html, _utils/invalidate-cloudfront-cache.sh
Resolves #33 
This is pending S3 details from Ops.
=> Build and deploy with Travis-CI

architecture/data-storage.md, architecture/fxa.md, architecture/sync.md
:wave: I was reading your docs and noticed some minor typos.
Most changes are in separate commits, just so there’s a way to provide some context for the change (like, in case of the Dexie link). I can squash them before merge if you want.
=> Fix Markdown and some typos

assets/main.scss
Hi,
This PR will fix the main concern of the issue #38.
I hope this help.
Resolves #38
=> Change of the button-link style to reflect 12em as percentage

.travis.yml, Gemfile, _utils/deploy.sh, s3_website.yml
Resolves #40 
This fixes the issue, but uses the completely different deployment setup.  There are too many issues with post-build installations in Travis-CI; instead this uses a deployment script with internal conditions.
=> Fix Travis-CI based deployment issues

process.md
Fixes #43 
Includes diagram from @changecourse describing the potential pre-development stages.
=> Update process doc to match scrum process

architecture/data-storage.md, architecture/fxa.md, architecture/index.md, architecture/lock-unlock.md, architecture/sync.md, process.md
=> Remove redundant H1s

_includes/footer.html, _includes/head.html, assets/main.scss
Resolves #63 
Depends on #62 
This updates the typography styling on the Lockbox site to utilize Photon standards (for web).
=> Photon styling updates

_config.yml, privacy.md
Resolves #57 
To be located at https://lockbox.firefox.com/privacy.html
=> Add Privacy Policy

_utils/startup.sh, faq.md
A start on expanding the details of what cryptographic tech is in use.
_started from [Hacker News](https://news.ycombinator.com/item?id=17500804)_
=> Expand on security technologies in use

architecture/index.md
Just keeping docs up to date with where things live.
=> Add Android to architecture table

faq.md
What do you think @nickbrandt? Feel free to tweak here directly on this branch if you have alternatives or suggestions.
=> add Android placeholder content for Alpha

architecture/index.md
per @sandysage and chat in Slack:
https://mozilla.slack.com/archives/C4LNYNJ8G/p1549506395403900?thread_ts=1549500206.400900&cid=C4LNYNJ8G
(site itself is now disabled and 404)
=> remove invalid extension website link

privacy.md
=> Revised privacy policy

privacy.md
Minor formatting and typo fixes
=> Privacy policy fixes

README.md, code_of_conduct.md
=> remove redundant COC file

addon/updates.json
=> Create updates.json for addon updates

addon/updates.json
=> specify minimum versions in update manifest

_config.yml, addon/updates.json
=> Addon 2.2.3 alpha

assets/main.scss
(showing hover state and footer border on home page)
=> UI changes to home page footer and addon button
